version: '3'
services:
  database:
    image: mysql:8.0.31-debian
    container_name: mysql
    ports:
      - '23306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database:/var/lib/mysql
