apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rsc-nginx
  name: rsc-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsc-nginx
  template:
    metadata:
      labels:
        app: rsc-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests: # 리소스 요청 설정
            memory: "200Mi"
            cpu: "1m"
          limits: # 리소스 제한 설정
            memory: "400Mi"
            cpu: "2m"
        ports:
        - containerPort: 80