apiVersion: v1
data:
  DB_Password: UGFzc3cwcmQhMA==
kind: Secret
metadata:
  name: db-secret
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-mysql
spec:
  containers:
  - image: mysql:5.6
    name: secret-mysql
    ports:
    - containerPort: 3306
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_Password
